# action.yml
name: 'CF Push'
description: 'Deploy an application to Cloud Foundry with a Manifest'
branding:
  icon: code
  color: blue
inputs:
  cf_api:
    description: 'API Endpoint for Cloud Foundry'
    required: true
  cf_user:
    description: 'Cloud Foundry Username'
    required: true
  cf_password:
    description: 'Cloud Foundry Password'
    required: true
  cf_org:
    description: 'Cloud Foundry Organization'
    required: true
  cf_space:
    description: 'Cloud Foundry Space'
    required: true
  manifest_file:
    description: 'Path and filename for Cloud Foundry manifest file'
    required: true
    default: './cf-manifest.yaml'
runs:
  using: 'composite'
  steps:
    - name: Log into Tanzu Platform
      run: ${{ github.action_path }}/cf-push.sh
      shell: bash
      env:
        CF_API: ${{ inputs.cf_api }}
        CF_USER: ${{ inputs.cf_user }}
        CF_PASSWORD: ${{ inputs.cf_password }}
        CF_ORG: ${{ inputs.cf_org }}
        CF_SPACE: ${{ inputs.cf_space }}
        MANIFEST_FILE: ${{ inputs.manifest_file }}
